# Generated by Django 3.1.5 on 2021-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210221_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimerText', models.TextField(max_length=1000)),
                ('disclaimerUpdateDate', models.DateTimeField()),
            ],
        ),
    ]
