# Generated by Django 3.1.5 on 2021-03-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='disclaimerUpdateDate',
        ),
        migrations.RemoveField(
            model_name='legal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='terms_accepted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='terms_accepted_date',
        ),
        migrations.AddField(
            model_name='legal',
            name='legal_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='legal',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.legal'),
            preserve_default=False,
        ),
    ]
