# Generated by Django 3.1.5 on 2021-03-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20210326_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('legal_id', models.AutoField(primary_key=True, serialize=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('disclaimer_text', models.TextField()),
                ('signature', jsignature.fields.JSignatureField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
