# Generated by Django 3.1.5 on 2021-03-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='signature',
        ),
    ]
