# Generated by Django 3.1.5 on 2021-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_legal_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='disclaimer_text',
            field=models.TextField(default='Employees are expressly required not to make defamatory statements and not to infringe or authorize any infringement of copyright or any other legal right by email communications. Employees who receive such an email must notify their supervisor immediately.'),
        ),
    ]
