# Generated by Django 3.1.5 on 2021-03-29 20:59

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210329_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
