# Generated by Django 3.1.5 on 2021-04-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_legal_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='signature',
        ),
        migrations.AddField(
            model_name='legal',
            name='email_confirmation',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
