# Generated by Django 3.1.5 on 2021-04-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210331_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='email_confirmation',
            field=models.EmailField(max_length=254),
        ),
    ]
