# Generated by Django 3.1.5 on 2021-02-17 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('cloud_web_panel', 'Cloud Web Panel'), ('hrl_subnet', 'HRL Subnet'), ('otu_Website', 'OTU Website')], max_length=20)),
                ('iprange', models.CharField(max_length=132)),
                ('ports', models.CharField(max_length=132)),
                ('hostname', models.CharField(max_length=253)),
                ('owner', models.CharField(choices=[('fbit', 'FBIT'), ('otu', 'OTU'), ('ssh', 'SSH')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('points', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('details', models.TextField(max_length=1012)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('asset', models.CharField(choices=[('cloud_web_panel', 'Cloud Web Panel'), ('hrl_subnet', 'HRL Subnet'), ('otu_Website', 'OTU Website')], max_length=20)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending_review', 'Pending review'), ('closed', 'Closed')], default='pending_review', max_length=32)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('classification', models.CharField(choices=[('xss', 'Cross-Site Scripting (XSS)'), ('injection', 'Injection'), ('broken_auth', 'Broken Authentication'), ('broken_ac', 'Broken Access Control'), ('sec_misconfiguration', 'Security Misconfiguration'), ('ssrf', 'Server Side Request Forgery (SSRF)'), ('logging_monitoring', 'Insufficient Logging and Monitoring'), ('insecure_deserialization', 'Insecure Deserialization'), ('sensitive_data_exposure', 'Sensitive Data Exposure'), ('rce', 'Remote Code Execution (RCE)')], max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
