# Generated by Django 3.1.5 on 2021-02-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/report_pics')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.report')),
            ],
        ),
    ]
