# Generated by Django 3.1.5 on 2021-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reportimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimages',
            name='image',
            field=models.ImageField(upload_to='report_pics'),
        ),
    ]
