# Generated by Django 3.1.5 on 2021-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210221_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimages',
            name='img',
        ),
        migrations.AddField(
            model_name='reportimages',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='report_pics'),
        ),
    ]
