# Generated by Django 3.1.5 on 2021-02-22 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210221_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(max_length=5012),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_a',
            field=models.ImageField(default='default.jpg', upload_to='report_pics', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='report',
            name='img_b',
            field=models.ImageField(default='default.jpg', upload_to='report_pics', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
