# Generated by Django 3.1.5 on 2021-03-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210221_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='img_a',
        ),
        migrations.RemoveField(
            model_name='report',
            name='img_b',
        ),
    ]
