# Generated by Django 3.1.5 on 2021-04-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210310_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('pending_review', 'Pending review'), ('closed', 'Closed')], default='pending_review', max_length=32),
        ),
    ]
