# Generated by Django 3.1.5 on 2021-04-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210406_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='asset',
            field=models.CharField(choices=[('cloud_web_panel', 'Cloud Web Panel'), ('hrl_subnet', 'HRL Subnet'), ('otu_Website', 'OTU Website'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='asset',
            field=models.CharField(choices=[('cloud_web_panel', 'Cloud Web Panel'), ('hrl_subnet', 'HRL Subnet'), ('otu_Website', 'OTU Website'), ('other', 'Other')], max_length=20),
        ),
    ]
